services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/src/config/.env
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"

volumes:
  mongo-data: # i will use this in future btw
